### ISSUE TITLE
content of uniprotkb_AND_reviewed_true_2023_07_03.tsv

### ISSUE THREAD

**Issue by igortru** [tymor22/protein-vec#1]
Hi, I don't see file on github.
which exact format it has?

meta_data_new = pd.read_csv('data/uniprotkb_AND_reviewed_true_2023_07_03.tsv', sep='\t')

**Comment by tymor22** [comment]
The file is too big for github. You can download it as follows:
wget https://users.flatironinstitute.org/thamamsy/public_www/uniprotkb_AND_reviewed_true_2023_07_03.tsv

**Comment by igortru** [comment]
thank you,
just some remarks :
1.
how much GPU memory requires your  tool?
I have 2 V100 16Gb , but it looks like not enough

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 230.00 MiB (GPU 0; 15.78 GiB total capacity; 14.46 GiB already allocated; 104.44 MiB free; 14.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

it looks like some selected proteins are very long for  my GPUs (set "after 2022-05-25")
len= 7760

2.
the installation requires lots of jumping with a drum
 
 scripts looks inaccurate
 for example:
FileNotFoundError: [Errno 2] No such file or directory: 'protein_vec_models/aspect_vec_gene3D_params.json'

should be 3d
protein_vec_models/aspect_vec_gene3d_params.json

**Comment by tymor22** [comment]
1) I️n general I️ don't recommend using these models for long sequences > ~ 2000 AA long, so I️ will add a line to filter out the very long protein sequences from that notebook. It sounds like the models were otherwise able to run on your V100. 
2) Thanks for that great catch - must have made a mistake copying things over. The paths have been updated to say "gene3d" instead of "gene3D".
